// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLMEFbLpsZvAeyIeLf_MuB0-b6dtsv1A',
    appId: '1:440513930885:web:52769cdb31744bd3532bec',
    messagingSenderId: '440513930885',
    projectId: 'cw03task',
    authDomain: 'cw03task.firebaseapp.com',
    storageBucket: 'cw03task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTkYj4ThnD6b2oFsRRC_BKcGM5aoyi2vo',
    appId: '1:440513930885:android:70a0e8822e3a0041532bec',
    messagingSenderId: '440513930885',
    projectId: 'cw03task',
    storageBucket: 'cw03task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GTI0E2uwOD2yK5KDkyOQPjFgDrM6_rU',
    appId: '1:440513930885:ios:7ace8745a74b9313532bec',
    messagingSenderId: '440513930885',
    projectId: 'cw03task',
    storageBucket: 'cw03task.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9GTI0E2uwOD2yK5KDkyOQPjFgDrM6_rU',
    appId: '1:440513930885:ios:7ace8745a74b9313532bec',
    messagingSenderId: '440513930885',
    projectId: 'cw03task',
    storageBucket: 'cw03task.firebasestorage.app',
    iosBundleId: 'com.example.cw03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLMEFbLpsZvAeyIeLf_MuB0-b6dtsv1A',
    appId: '1:440513930885:web:830c8168dd2e149e532bec',
    messagingSenderId: '440513930885',
    projectId: 'cw03task',
    authDomain: 'cw03task.firebaseapp.com',
    storageBucket: 'cw03task.firebasestorage.app',
  );
}
